 # Uncomment this line to define a global platform for your project
# platform :ios, "7.0"
platform :ios, "13.0"
use_frameworks!

target "Health UX Kit" do
    pod "iOSCommonUI"
    pod 'Material'

target 'Health UX KitTests' do
inherit! :search_paths
end
end
